# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :City => " cities.first)
Category.create(:id => 1, :category => "Diseno Grafico", :parent_id => '')
Category.create(:id => 2, :category => "Ilustracion", :parent_id => '')
Category.create(:id => 3, :category => "Diseno web", :parent_id => '')
Category.create(:id => 4, :category => "Programacion web", :parent_id => '')
Category.create(:id => 5, :category => "Animacion", :parent_id => '')
Category.create(:id => 6, :category => "Diseno Industrial", :parent_id => '')
Category.create(:id => 7, :category => "Fotografia", :parent_id => '')
Category.create(:id => 8, :category => "Redaccion", :parent_id => '')

Country.create(:id => 1	,	:country => "Bogota D.C")
Country.create(:id => 2	,	:country => "Antioquia")
Country.create(:id => 3	,	:country => "Valle del Cauca")
Country.create(:id => 4	,	:country => "Atlantic")
Country.create(:id => 5	,	:country => "Bolivar")
Country.create(:id => 6	,	:country => "Norte de Santander")
Country.create(:id => 7	,	:country => "Tolima")
Country.create(:id => 8	,	:country => "Santande")
Country.create(:id => 9	,	:country => "Cundinamarca")
Country.create(:id => 10	,	:country => "Risaralda")
Country.create(:id => 11	,	:country => "Magdalena")
Country.create(:id => 12	,	:country => "Meta")
Country.create(:id => 13	,	:country => "Cesar")
Country.create(:id => 14	,	:country => "Narino")
Country.create(:id => 15	,	:country => "Cordova")
Country.create(:id => 16	,	:country => "Caldas")
Country.create(:id => 17	,	:country => "Huila")
Country.create(:id => 18	,	:country => "Quindio")
Country.create(:id => 19	,	:country => "Cauca")
Country.create(:id => 20	,	:country => "Sucre")
Country.create(:id => 21	,	:country => "La Guajira")
Country.create(:id => 22	,	:country => "Boyaca")
Country.create(:id => 23	,	:country => "Caqueta")
Country.create(:id => 24	,	:country => "Casanare")
Country.create(:id => 25	,	:country => "Choco")
Country.create(:id => 26	,	:country => "Arauca")
Country.create(:id => 27	,	:country => "San Andres y Providencia")
Country.create(:id => 28	,	:country => "Guaviare")
Country.create(:id => 29	,	:country => "Putumayo")
Country.create(:id => 30	,	:country => "Amazonas")
Country.create(:id => 31	,	:country => "Vichada")
Country.create(:id => 32	,	:country => "Vaupes")
Country.create(:id => 33	,	:country => "Guainia")

City.create(:id => 1	,:country_id => 1	,:city => "	Bogota")
City.create(:id => 2	,:country_id => 2	,:city => "	Medellin")
City.create(:id => 3	,:country_id => 2	,:city => "	Bello")
City.create(:id => 4	,:country_id => 2	,:city => "	Envigado")
City.create(:id => 5	,:country_id => 2	,:city => "	Apartado")
City.create(:id => 6	,:country_id => 2	,:city => "	Turbo")
City.create(:id => 7	,:country_id => 2	,:city => "	Rionegro")
City.create(:id => 8	,:country_id => 2	,:city => "	Caucasia")
City.create(:id => 9	,:country_id => 2	,:city => "	Caldas")
City.create(:id => 10	,:country_id => 2	,:city => "	Chigorodo")
City.create(:id => 11	,:country_id => 2	,:city => "	Copacabana")
City.create(:id => 12	,:country_id => 2	,:city => "	La Estrella")
City.create(:id => 13	,:country_id => 2	,:city => "	Necocli")
City.create(:id => 14	,:country_id => 2	,:city => "	Carepa")
City.create(:id => 15	,:country_id => 2	,:city => "	Marinilla")
City.create(:id => 16	,:country_id => 2	,:city => "	La Ceja")
City.create(:id => 17	,:country_id => 2	,:city => "	Girardota")
City.create(:id => 18	,:country_id => 2	,:city => "	La Estrella")
City.create(:id => 19	,:country_id => 2	,:city => "	Necocli")
City.create(:id => 20	,:country_id => 2	,:city => "	La Ceja")
City.create(:id => 21	,:country_id => 2	,:city => "	El Bagre")
City.create(:id => 22	,:country_id => 2	,:city => "	Marinilla")
City.create(:id => 23	,:country_id => 2	,:city => "	Sabaneta")
City.create(:id => 24	,:country_id => 2	,:city => "	Carepa")
City.create(:id => 25	,:country_id => 2	,:city => "	Girardota")
City.create(:id => 26	,:country_id => 2	,:city => "	Barbosa")
City.create(:id => 27	,:country_id => 2	,:city => "	Andes")
City.create(:id => 28	,:country_id => 2	,:city => "	Yarumal")
City.create(:id => 29	,:country_id => 2	,:city => "	El Carmen de Viboral")
City.create(:id => 30	,:country_id => 2	,:city => "	Guarne")
City.create(:id => 31	,:country_id => 2	,:city => "	Puerto Berrio")
City.create(:id => 32	,:country_id => 2	,:city => "	Urrao")
City.create(:id => 33	,:country_id => 2	,:city => "	Sonson")
City.create(:id => 34	,:country_id => 2	,:city => "	Segovia")
City.create(:id => 35	,:country_id => 2	,:city => "	Taraza")
City.create(:id => 36	,:country_id => 2	,:city => "	Santa Rosa de Osos")
City.create(:id => 37	,:country_id => 2	,:city => "	Arboletes")
City.create(:id => 38	,:country_id => 2	,:city => "	Caceres")
City.create(:id => 39	,:country_id => 2	,:city => "	San Pedro de Uraba")
City.create(:id => 40	,:country_id => 2	,:city => "	Ciudad Bolivar")
City.create(:id => 41	,:country_id => 2	,:city => "	Amaga")
City.create(:id => 42	,:country_id => 2	,:city => "	Zaragoza")
City.create(:id => 43	,:country_id => 2	,:city => "	El Santuario")
City.create(:id => 44	,:country_id => 2	,:city => "	Ituango")
City.create(:id => 45	,:country_id => 2	,:city => "	Dabeiba")
City.create(:id => 46	,:country_id => 2	,:city => "	Santa Barbara")
City.create(:id => 47	,:country_id => 2	,:city => "	Santa Fe de Antioquia")
City.create(:id => 48	,:country_id => 2	,:city => "	Remedios")
City.create(:id => 49	,:country_id => 2	,:city => "	Fredonia")
City.create(:id => 50	,:country_id => 2	,:city => "	San Pedro")
City.create(:id => 51	,:country_id => 2	,:city => "	Concordia")
City.create(:id => 52	,:country_id => 2	,:city => "	San Juan de Uraba")
City.create(:id => 53	,:country_id => 2	,:city => "	Nechi")
City.create(:id => 54	,:country_id => 2	,:city => "	Amalfi")
City.create(:id => 55	,:country_id => 2	,:city => "	Abejorral")
City.create(:id => 56	,:country_id => 2	,:city => "	Frontino")
City.create(:id => 57	,:country_id => 2	,:city => "	Yolombo")
City.create(:id => 58	,:country_id => 2	,:city => "	San Vicente")
City.create(:id => 59	,:country_id => 2	,:city => "	Salgar")
City.create(:id => 60	,:country_id => 2	,:city => "	San Roque")
City.create(:id => 61	,:country_id => 2	,:city => "	La Union")
City.create(:id => 62	,:country_id => 2	,:city => "	Don Matias")
City.create(:id => 63	,:country_id => 2	,:city => "	Valdivia")
City.create(:id => 64	,:country_id => 2	,:city => "	Canasgordas")
City.create(:id => 65	,:country_id => 2	,:city => "	Betulia")
City.create(:id => 66	,:country_id => 2	,:city => "	Puerto Nare")
City.create(:id => 67	,:country_id => 2	,:city => "	Mutata1")
City.create(:id => 68	,:country_id => 2	,:city => "	Tamesis")
City.create(:id => 69	,:country_id => 2	,:city => "	Puerto Triunfo")
City.create(:id => 70	,:country_id => 2	,:city => "	Penol")
City.create(:id => 71	,:country_id => 2	,:city => "	San Carlos")
City.create(:id => 72	,:country_id => 2	,:city => "	Narino")
City.create(:id => 73	,:country_id => 2	,:city => "	Cocorna")
City.create(:id => 74	,:country_id => 2	,:city => "	Yondo")
City.create(:id => 75	,:country_id => 2	,:city => "	Anori")
City.create(:id => 76	,:country_id => 2	,:city => "	Jardin")
City.create(:id => 77	,:country_id => 2	,:city => "	San Rafael")
City.create(:id => 78	,:country_id => 2	,:city => "	Venecia")
City.create(:id => 79	,:country_id => 2	,:city => "	Sopetran")
City.create(:id => 80	,:country_id => 2	,:city => "	Titiribi")
City.create(:id => 81	,:country_id => 2	,:city => "	Jerico")
City.create(:id => 82	,:country_id => 2	,:city => "	Angostura")
City.create(:id => 83	,:country_id => 2	,:city => "	Ebejico")
City.create(:id => 84	,:country_id => 2	,:city => "	San Jeronimo")
City.create(:id => 85	,:country_id => 2	,:city => "	Santo Domingo")
City.create(:id => 86	,:country_id => 2	,:city => "	Vegachi")
City.create(:id => 87	,:country_id => 2	,:city => "	Gomez Plata")
City.create(:id => 88	,:country_id => 2	,:city => "	San Luis")
City.create(:id => 89	,:country_id => 2	,:city => "	Betania")
City.create(:id => 90	,:country_id => 2	,:city => "	Argelia")
City.create(:id => 91	,:country_id => 2	,:city => "	Granada")
City.create(:id => 92	,:country_id => 2	,:city => "	Campamento")
City.create(:id => 93	,:country_id => 2	,:city => "	Cisneros")
City.create(:id => 94	,:country_id => 2	,:city => "	Peque")
City.create(:id => 95	,:country_id => 2	,:city => "	Liborina")
City.create(:id => 96	,:country_id => 2	,:city => "	Briceno")
City.create(:id => 97	,:country_id => 2	,:city => "	Entrerrios")
City.create(:id => 98	,:country_id => 2	,:city => "	Uramita")
City.create(:id => 99	,:country_id => 2	,:city => "	Pueblorrico")
City.create(:id => 100	,:country_id => 2	,:city => "	Sabanalarga")
City.create(:id => 101	,:country_id => 2	,:city => "	Yali")
City.create(:id => 102	,:country_id => 2	,:city => "	Caicedo")
City.create(:id => 103	,:country_id => 2	,:city => "	Angelopolis")
City.create(:id => 104	,:country_id => 2	,:city => "	Maceo")
City.create(:id => 105	,:country_id => 2	,:city => "	Montebello")
City.create(:id => 106	,:country_id => 2	,:city => "	Anza")
City.create(:id => 107	,:country_id => 2	,:city => "	San Andres de Cuerquia")
City.create(:id => 108	,:country_id => 2	,:city => "	Tarso")
City.create(:id => 109	,:country_id => 2	,:city => "	La Pintada")
City.create(:id => 110	,:country_id => 2	,:city => "	Buritica")
City.create(:id => 111	,:country_id => 2	,:city => "	Heliconia")
City.create(:id => 112	,:country_id => 2	,:city => "	San Francisco")
City.create(:id => 113	,:country_id => 2	,:city => "	Valparaiso")
City.create(:id => 114	,:country_id => 2	,:city => "	Guadalupe")
City.create(:id => 115	,:country_id => 2	,:city => "	Belmira")
City.create(:id => 116	,:country_id => 2	,:city => "	Guatape")
City.create(:id => 117	,:country_id => 2	,:city => "	Toledo")
City.create(:id => 118	,:country_id => 2	,:city => "	Caramanta")
City.create(:id => 119	,:country_id => 2	,:city => "	Vigia del Fuerte")
City.create(:id => 120	,:country_id => 2	,:city => "	Armenia")
City.create(:id => 121	,:country_id => 2	,:city => "	Caracoli")
City.create(:id => 122	,:country_id => 2	,:city => "	Hispania")
City.create(:id => 123	,:country_id => 2	,:city => "	Concepcion")
City.create(:id => 124	,:country_id => 2	,:city => "	Giraldo")
City.create(:id => 125	,:country_id => 2	,:city => "	Carolina")
City.create(:id => 126	,:country_id => 2	,:city => "	Alejandria")
City.create(:id => 127	,:country_id => 2	,:city => "	Murindo")
City.create(:id => 128	,:country_id => 2	,:city => "	San Jose de La Montana")
City.create(:id => 129	,:country_id => 2	,:city => "	Olaya")
City.create(:id => 130	,:country_id => 2	,:city => "	Abriaqui")
City.create(:id => 131	,:country_id => 3	,:city => "	Cali")
City.create(:id => 132	,:country_id => 3	,:city => "	Buenaventura")
City.create(:id => 133	,:country_id => 3	,:city => "	Palmira")
City.create(:id => 134	,:country_id => 3	,:city => "	Tulua")
City.create(:id => 135	,:country_id => 3	,:city => "	Cartago")
City.create(:id => 136	,:country_id => 3	,:city => "	Guadalajara de Buga")
City.create(:id => 137	,:country_id => 3	,:city => "	Jamundi")
City.create(:id => 138	,:country_id => 3	,:city => "	Yumbo")
City.create(:id => 139	,:country_id => 3	,:city => "	Candelaria")
City.create(:id => 140	,:country_id => 3	,:city => "	Florida")
City.create(:id => 141	,:country_id => 3	,:city => "	El Cerrito")
City.create(:id => 142	,:country_id => 3	,:city => "	Pradera")
City.create(:id => 143	,:country_id => 3	,:city => "	Florida")
City.create(:id => 144	,:country_id => 3	,:city => "	El Cerrito")
City.create(:id => 145	,:country_id => 3	,:city => "	Pradera")
City.create(:id => 146	,:country_id => 3	,:city => "	Sevilla")
City.create(:id => 147	,:country_id => 3	,:city => "	Zarzal")
City.create(:id => 148	,:country_id => 3	,:city => "	Dagua")
City.create(:id => 149	,:country_id => 3	,:city => "	Roldanillo")
City.create(:id => 150	,:country_id => 3	,:city => "	Guacari")
City.create(:id => 151	,:country_id => 3	,:city => "	La Union")
City.create(:id => 152	,:country_id => 3	,:city => "	Caicedonia")
City.create(:id => 153	,:country_id => 3	,:city => "	Bugalagrande")
City.create(:id => 154	,:country_id => 3	,:city => "	Ansermanuevo")
City.create(:id => 155	,:country_id => 3	,:city => "	Ginebra")
City.create(:id => 156	,:country_id => 3	,:city => "	Trujillo")
City.create(:id => 157	,:country_id => 3	,:city => "	Andalucia")
City.create(:id => 158	,:country_id => 3	,:city => "	Alcala")
City.create(:id => 159	,:country_id => 3	,:city => "	Riofrio")
City.create(:id => 160	,:country_id => 3	,:city => "	Toro")
City.create(:id => 161	,:country_id => 3	,:city => "	Restrepo")
City.create(:id => 162	,:country_id => 3	,:city => "	San Pedro")
City.create(:id => 163	,:country_id => 3	,:city => "	Yotoco")
City.create(:id => 164	,:country_id => 3	,:city => "	Darien")
City.create(:id => 165	,:country_id => 3	,:city => "	Bolivar")
City.create(:id => 166	,:country_id => 3	,:city => "	Obando")
City.create(:id => 167	,:country_id => 3	,:city => "	La Victoria")
City.create(:id => 168	,:country_id => 3	,:city => "	La Cumbre")
City.create(:id => 169	,:country_id => 3	,:city => "	El aguila")
City.create(:id => 170	,:country_id => 3	,:city => "	El Dovio")
City.create(:id => 171	,:country_id => 3	,:city => "	El Cairo")
City.create(:id => 172	,:country_id => 3	,:city => "	Versalles")
City.create(:id => 173	,:country_id => 3	,:city => "	Argelia")
City.create(:id => 174	,:country_id => 3	,:city => "	Barranquilla")
City.create(:id => 175	,:country_id => 3	,:city => "	Soledad")
City.create(:id => 176	,:country_id => 3	,:city => "	Malambo")
City.create(:id => 177	,:country_id => 3	,:city => "	Baranoa")
City.create(:id => 178	,:country_id => 3	,:city => "	Galapa")
City.create(:id => 179	,:country_id => 3	,:city => "	Puerto Colombia")
City.create(:id => 180	,:country_id => 3	,:city => "	Sabanagrande")
City.create(:id => 181	,:country_id => 3	,:city => "	Santo Tomas")
City.create(:id => 182	,:country_id => 3	,:city => "	Palmar de Varela")
City.create(:id => 183	,:country_id => 3	,:city => "	Luruaco")
City.create(:id => 184	,:country_id => 3	,:city => "	Repelon")
City.create(:id => 185	,:country_id => 3	,:city => "	Campo de La Cruz")
City.create(:id => 186	,:country_id => 3	,:city => "	Ponedera")
City.create(:id => 187	,:country_id => 3	,:city => "	Juan de Acosta")
City.create(:id => 188	,:country_id => 3	,:city => "	Polonuevo")
City.create(:id => 189	,:country_id => 3	,:city => "	Manati")
City.create(:id => 190	,:country_id => 3	,:city => "	Santa Lucia")
City.create(:id => 191	,:country_id => 3	,:city => "	Candelaria")
City.create(:id => 192	,:country_id => 3	,:city => "	Tubara")
City.create(:id => 193	,:country_id => 3	,:city => "	Suan")
City.create(:id => 194	,:country_id => 3	,:city => "	Piojo")
City.create(:id => 195	,:country_id => 4	,:city => "	Barranquilla")
City.create(:id => 196	,:country_id => 4	,:city => "	Soledad")
City.create(:id => 197	,:country_id => 4	,:city => "	Malambo")
City.create(:id => 198	,:country_id => 4	,:city => "	Baranoa")
City.create(:id => 199	,:country_id => 4	,:city => "	Galapa")
City.create(:id => 200	,:country_id => 4	,:city => "	Puerto Colombia")
City.create(:id => 201	,:country_id => 4	,:city => "	Sabanagrande")
City.create(:id => 202	,:country_id => 4	,:city => "	Santo Tomas")
City.create(:id => 203	,:country_id => 4	,:city => "	Palmar de Varela")
City.create(:id => 204	,:country_id => 4	,:city => "	Luruaco")
City.create(:id => 205	,:country_id => 4	,:city => "	Campo de La Cruz")
City.create(:id => 206	,:country_id => 4	,:city => "	Ponedera")
City.create(:id => 207	,:country_id => 4	,:city => "	Juan de Acosta")
City.create(:id => 208	,:country_id => 4	,:city => "	Polonuevo")
City.create(:id => 209	,:country_id => 4	,:city => "	Manati")
City.create(:id => 210	,:country_id => 4	,:city => "	Santa Lucia")
City.create(:id => 211	,:country_id => 4	,:city => "	Candelaria")
City.create(:id => 212	,:country_id => 4	,:city => "	Tubara,Suan")
City.create(:id => 213	,:country_id => 4	,:city => "	Piojo")
City.create(:id => 214	,:country_id => 5	,:city => "	Cartagena de Indias")
City.create(:id => 215	,:country_id => 5	,:city => "	Magangue")
City.create(:id => 216	,:country_id => 5	,:city => "	Turbaco")
City.create(:id => 217	,:country_id => 5	,:city => "	Arjona")
City.create(:id => 218	,:country_id => 5	,:city => "	Maria La Baja")
City.create(:id => 219	,:country_id => 5	,:city => "	Santa Cruz de Mompox")
City.create(:id => 220	,:country_id => 5	,:city => "	Santa Rosa del Sur")
City.create(:id => 221	,:country_id => 5	,:city => "	San Juan Nepomuceno")
City.create(:id => 222	,:country_id => 5	,:city => "	San Pablo")
City.create(:id => 223	,:country_id => 5	,:city => "	Pinillos")
City.create(:id => 224	,:country_id => 5	,:city => "	San Jacinto")
City.create(:id => 225	,:country_id => 5	,:city => "	Rio Viejo")
City.create(:id => 226	,:country_id => 5	,:city => "	Calamar")
City.create(:id => 227	,:country_id => 5	,:city => "	Achi")
City.create(:id => 228	,:country_id => 5	,:city => "	Morales")
City.create(:id => 229	,:country_id => 5	,:city => "	Simiti")
City.create(:id => 230	,:country_id => 5	,:city => "	Santa Rosa")
City.create(:id => 231	,:country_id => 5	,:city => "	Villanueva")
City.create(:id => 232	,:country_id => 5	,:city => "	Montecristo")
City.create(:id => 233	,:country_id => 5	,:city => "	Arenal del Sur")
City.create(:id => 234	,:country_id => 5	,:city => "	San Estanislao")
City.create(:id => 235	,:country_id => 5	,:city => "	Barranco de Loba")
City.create(:id => 236	,:country_id => 5	,:city => "	San Martin de Loba")
City.create(:id => 237	,:country_id => 5	,:city => "	Turbana")
City.create(:id => 238	,:country_id => 5	,:city => "	Cordoba")
City.create(:id => 239	,:country_id => 5	,:city => "	San Fernando")
City.create(:id => 240	,:country_id => 5	,:city => "	Santa Catalina")
City.create(:id => 241	,:country_id => 5	,:city => "	Clemencia")
City.create(:id => 242	,:country_id => 5	,:city => "	Hatillo de Loba")
City.create(:id => 243	,:country_id => 5	,:city => "	Altos del Rosario")
City.create(:id => 244	,:country_id => 5	,:city => "	Zambrano")
City.create(:id => 245	,:country_id => 5	,:city => "	Cicuco")
City.create(:id => 246	,:country_id => 5	,:city => "	Talaigua Nuevo")
City.create(:id => 247	,:country_id => 5	,:city => "	San Jacinto del Cauca")
City.create(:id => 248	,:country_id => 5	,:city => "	Arroyohondo")
City.create(:id => 249	,:country_id => 5	,:city => "	Regidor")
City.create(:id => 250	,:country_id => 5	,:city => "	Soplaviento")
City.create(:id => 251	,:country_id => 5	,:city => "	El Guamo")
City.create(:id => 252	,:country_id => 5	,:city => "	Cantagallo")
City.create(:id => 253	,:country_id => 5	,:city => "	El Penon")
City.create(:id => 254	,:country_id => 6	,:city => "	San Jose de Cucuta")
City.create(:id => 255	,:country_id => 6	,:city => "	Ocana")
City.create(:id => 256	,:country_id => 6	,:city => "	Villa del Rosario")
City.create(:id => 257	,:country_id => 6	,:city => "	Los Patios")
City.create(:id => 258	,:country_id => 6	,:city => "	Pamplona")
City.create(:id => 259	,:country_id => 6	,:city => "	Tibu")
City.create(:id => 260	,:country_id => 6	,:city => "	Abrego")
City.create(:id => 261	,:country_id => 6	,:city => "	Sardinata")
City.create(:id => 262	,:country_id => 6	,:city => "	El Zulia")
City.create(:id => 263	,:country_id => 6	,:city => "	Teorama")
City.create(:id => 264	,:country_id => 6	,:city => "	Toledo")
City.create(:id => 265	,:country_id => 6	,:city => "	Convencion")
City.create(:id => 266	,:country_id => 6	,:city => "	El Carmen")
City.create(:id => 267	,:country_id => 6	,:city => "	Chinacota")
City.create(:id => 268	,:country_id => 6	,:city => "	San Calixto")
City.create(:id => 269	,:country_id => 6	,:city => "	La Esperanza")
City.create(:id => 270	,:country_id => 6	,:city => "	El Tarra")
City.create(:id => 271	,:country_id => 6	,:city => "	Cachira")
City.create(:id => 272	,:country_id => 6	,:city => "	Chitaga")
City.create(:id => 273	,:country_id => 6	,:city => "	Hacari")
City.create(:id => 274	,:country_id => 6	,:city => "	Salazar de Las Palmas")
City.create(:id => 275	,:country_id => 6	,:city => "	Arboledas")
City.create(:id => 276	,:country_id => 6	,:city => "	Puerto Santander")
City.create(:id => 277	,:country_id => 6	,:city => "	Cucutilla")
City.create(:id => 278	,:country_id => 6	,:city => "	La Playa")
City.create(:id => 279	,:country_id => 6	,:city => "	Ragonvalia")
City.create(:id => 280	,:country_id => 6	,:city => "	Bochalema")
City.create(:id => 281	,:country_id => 6	,:city => "	Gramalote")
City.create(:id => 282	,:country_id => 6	,:city => "	Labateca")
City.create(:id => 283	,:country_id => 6	,:city => "	Silos")
City.create(:id => 284	,:country_id => 6	,:city => "	Villa Caro")
City.create(:id => 285	,:country_id => 6	,:city => "	Pamplonita")
City.create(:id => 286	,:country_id => 6	,:city => "	Bucarasica")
City.create(:id => 287	,:country_id => 6	,:city => "	Herran")
City.create(:id => 288	,:country_id => 6	,:city => "	San Cayetano")
City.create(:id => 289	,:country_id => 6	,:city => "	Durania")
City.create(:id => 290	,:country_id => 6	,:city => "	Mutiscua")
City.create(:id => 291	,:country_id => 6	,:city => "	Lourdes")
City.create(:id => 292	,:country_id => 6	,:city => "	Santiago")
City.create(:id => 293	,:country_id => 6	,:city => "	Cacota")
City.create(:id => 294	,:country_id => 7	,:city => "	Ibague")
City.create(:id => 295	,:country_id => 7	,:city => "	Espinal")
City.create(:id => 296	,:country_id => 7	,:city => "	Chaparral")
City.create(:id => 297	,:country_id => 7	,:city => "	Libano")
City.create(:id => 298	,:country_id => 7	,:city => "	Guamo")
City.create(:id => 299	,:country_id => 7	,:city => "	Ortega")
City.create(:id => 300	,:country_id => 7	,:city => "	Mariquita")
City.create(:id => 301	,:country_id => 7	,:city => "	Melgar")
City.create(:id => 302	,:country_id => 7	,:city => "	Fresno")
City.create(:id => 303	,:country_id => 7	,:city => "	Planadas")
City.create(:id => 304	,:country_id => 7	,:city => "	Coyaima")
City.create(:id => 305	,:country_id => 7	,:city => "	Flandes")
City.create(:id => 306	,:country_id => 7	,:city => "	Purificacion")
City.create(:id => 307	,:country_id => 7	,:city => "	Honda")
City.create(:id => 308	,:country_id => 7	,:city => "	Rioblanco")
City.create(:id => 309	,:country_id => 7	,:city => "	Natagaima")
City.create(:id => 310	,:country_id => 7	,:city => "	Ataco")
City.create(:id => 311	,:country_id => 7	,:city => "	Rovira")
City.create(:id => 312	,:country_id => 7	,:city => "	Cajamarca")
City.create(:id => 313	,:country_id => 7	,:city => "	Lerida")
City.create(:id => 314	,:country_id => 7	,:city => "	San Luis")
City.create(:id => 315	,:country_id => 7	,:city => "	Venadillo")
City.create(:id => 316	,:country_id => 7	,:city => "	San Antonio")
City.create(:id => 317	,:country_id => 7	,:city => "	Saldana")
City.create(:id => 318	,:country_id => 7	,:city => "	Icononzo")
City.create(:id => 319	,:country_id => 7	,:city => "	Villahermosa")
City.create(:id => 320	,:country_id => 7	,:city => "	Cunday")
City.create(:id => 321	,:country_id => 7	,:city => "	Palocabildo")
City.create(:id => 322	,:country_id => 7	,:city => "	Falan,Dolores")
City.create(:id => 323	,:country_id => 7	,:city => "	Herveo")
City.create(:id => 324	,:country_id => 7	,:city => "	Coello")
City.create(:id => 325	,:country_id => 7	,:city => "	Alvarado")
City.create(:id => 326	,:country_id => 7	,:city => "	Carmen de Apicala")
City.create(:id => 327	,:country_id => 7	,:city => "	Ambalema")
City.create(:id => 328	,:country_id => 7	,:city => "	Casabianca")
City.create(:id => 329	,:country_id => 7	,:city => "	Santa Isabel")
City.create(:id => 330	,:country_id => 7	,:city => "	Roncesvalles")
City.create(:id => 331	,:country_id => 7	,:city => "	Villarrica")
City.create(:id => 332	,:country_id => 7	,:city => "	Valle de San Juan")
City.create(:id => 333	,:country_id => 7	,:city => "	Piedras")
City.create(:id => 334	,:country_id => 7	,:city => "	Alpujarra")
City.create(:id => 335	,:country_id => 7	,:city => "	Murillo")
City.create(:id => 336	,:country_id => 7	,:city => "	Suarez")
City.create(:id => 337	,:country_id => 8	,:city => "	Bucaramanga")
City.create(:id => 338	,:country_id => 8	,:city => "	Floridablanca")
City.create(:id => 339	,:country_id => 8	,:city => "	Barrancabermeja")
City.create(:id => 340	,:country_id => 8	,:city => "	Giron")
City.create(:id => 341	,:country_id => 8	,:city => "	Piedecuesta")
City.create(:id => 342	,:country_id => 8	,:city => "	Cimitarra")
City.create(:id => 343	,:country_id => 8	,:city => "	San Vicente de Chucuri")
City.create(:id => 344	,:country_id => 8	,:city => "	Puerto Wilches")
City.create(:id => 345	,:country_id => 8	,:city => "	Lebrija")
City.create(:id => 346	,:country_id => 8	,:city => "	Rionegro")
City.create(:id => 347	,:country_id => 8	,:city => "	Socorro")
City.create(:id => 348	,:country_id => 8	,:city => "	Barbosa")
City.create(:id => 349	,:country_id => 8	,:city => "	Sabana de Torres")
City.create(:id => 350	,:country_id => 8	,:city => "	Velez,Malaga")
City.create(:id => 351	,:country_id => 8	,:city => "	El Carmen de Chucuri")
City.create(:id => 352	,:country_id => 8	,:city => "	Landazuri")
City.create(:id => 353	,:country_id => 8	,:city => "	Puente Nacional")
City.create(:id => 354	,:country_id => 8	,:city => "	Bolivar")
City.create(:id => 355	,:country_id => 8	,:city => "	El Playon")
City.create(:id => 356	,:country_id => 8	,:city => "	Curiti")
City.create(:id => 357	,:country_id => 8	,:city => "	Charala")
City.create(:id => 358	,:country_id => 8	,:city => "	Oiba")
City.create(:id => 359	,:country_id => 8	,:city => "	Los Santos")
City.create(:id => 360	,:country_id => 8	,:city => "	Suaita")
City.create(:id => 361	,:country_id => 8	,:city => "	Mogotes")
City.create(:id => 362	,:country_id => 8	,:city => "	San Andres")
City.create(:id => 363	,:country_id => 8	,:city => "	Zapatoca")
City.create(:id => 364	,:country_id => 8	,:city => "	Sucre")
City.create(:id => 365	,:country_id => 8	,:city => "	Simacota")
City.create(:id => 366	,:country_id => 8	,:city => "	La Belleza")
City.create(:id => 367	,:country_id => 8	,:city => "	Aratoca")
City.create(:id => 368	,:country_id => 8	,:city => "	Barichara")
City.create(:id => 369	,:country_id => 8	,:city => "	Coromoro")
City.create(:id => 370	,:country_id => 8	,:city => "	Villanueva")
City.create(:id => 371	,:country_id => 8	,:city => "	Guaca")
City.create(:id => 372	,:country_id => 8	,:city => "	Tona")
City.create(:id => 373	,:country_id => 8	,:city => "	Puerto Parra")
City.create(:id => 374	,:country_id => 8	,:city => "	Florian")
City.create(:id => 375	,:country_id => 8	,:city => "	Cerrito")
City.create(:id => 376	,:country_id => 8	,:city => "	Capitanejo")
City.create(:id => 377	,:country_id => 8	,:city => "	Concepcion")
City.create(:id => 378	,:country_id => 8	,:city => "	Matanza")
City.create(:id => 379	,:country_id => 8	,:city => "	Molagavita")
City.create(:id => 380	,:country_id => 8	,:city => "	Onzaga")
City.create(:id => 381	,:country_id => 8	,:city => "	La Paz")
City.create(:id => 382	,:country_id => 8	,:city => "	El Penon")
City.create(:id => 383	,:country_id => 8	,:city => "	Guadalupe")
City.create(:id => 384	,:country_id => 8	,:city => "	Betulia")
City.create(:id => 385	,:country_id => 8	,:city => "	Carcasi")
City.create(:id => 386	,:country_id => 8	,:city => "	Gambita")
City.create(:id => 387	,:country_id => 8	,:city => "	Chipata")
City.create(:id => 388	,:country_id => 8	,:city => "	Ocamonte")
City.create(:id => 389	,:country_id => 8	,:city => "	San Jose de Miranda")
City.create(:id => 390	,:country_id => 8	,:city => "	Albania")
City.create(:id => 391	,:country_id => 8	,:city => "	Santa Helena del Opon")
City.create(:id => 392	,:country_id => 8	,:city => "	Pinchote")
City.create(:id => 393	,:country_id => 8	,:city => "	Guavata")
City.create(:id => 394	,:country_id => 8	,:city => "	Contratacion")
City.create(:id => 395	,:country_id => 8	,:city => "	Enciso")
City.create(:id => 396	,:country_id => 8	,:city => "	San Benito")
City.create(:id => 397	,:country_id => 8	,:city => "	Paramo")
City.create(:id => 398	,:country_id => 8	,:city => "	Surata")
City.create(:id => 399	,:country_id => 8	,:city => "	Jesus Maria")
City.create(:id => 400	,:country_id => 8	,:city => "	Chima")
City.create(:id => 401	,:country_id => 8	,:city => "	Charta")
City.create(:id => 402	,:country_id => 8	,:city => "	Galan")
City.create(:id => 403	,:country_id => 8	,:city => "	San Joaquin")
City.create(:id => 404	,:country_id => 8	,:city => "	Palmar")
City.create(:id => 405	,:country_id => 8	,:city => "	Confines")
City.create(:id => 406	,:country_id => 8	,:city => "	Macaravita")
City.create(:id => 407	,:country_id => 8	,:city => "	Encino")
City.create(:id => 408	,:country_id => 8	,:city => "	San Miguel")
City.create(:id => 409	,:country_id => 8	,:city => "	Palmas del Socorro")
City.create(:id => 410	,:country_id => 8	,:city => "	Hato")
City.create(:id => 411	,:country_id => 8	,:city => "	Vetas")
City.create(:id => 412	,:country_id => 8	,:city => "	Santa Barbara")
City.create(:id => 413	,:country_id => 8	,:city => "	El Guacamayo")
City.create(:id => 414	,:country_id => 8	,:city => "	Guapota")
City.create(:id => 415	,:country_id => 8	,:city => "	Aguada")
City.create(:id => 416	,:country_id => 8	,:city => "	Cepita")
City.create(:id => 417	,:country_id => 8	,:city => "	Cabrera")
City.create(:id => 418	,:country_id => 8	,:city => "	California")
City.create(:id => 419	,:country_id => 8	,:city => "	Jordan")
City.create(:id => 420	,:country_id => 9	,:city => "	Soacha")
City.create(:id => 421	,:country_id => 9	,:city => "	Fusagasuga")
City.create(:id => 422	,:country_id => 9	,:city => "	Facatativa")
City.create(:id => 423	,:country_id => 9	,:city => "	Chia")
City.create(:id => 424	,:country_id => 9	,:city => "	Zipaquira")
City.create(:id => 425	,:country_id => 9	,:city => "	Girardot")
City.create(:id => 426	,:country_id => 9	,:city => "	Mosquera")
City.create(:id => 427	,:country_id => 9	,:city => "	Madrid")
City.create(:id => 428	,:country_id => 9	,:city => "	Funza")
City.create(:id => 429	,:country_id => 9	,:city => "	Cajica")
City.create(:id => 430	,:country_id => 9	,:city => "	Villa de San Diego de Ubate")
City.create(:id => 431	,:country_id => 9	,:city => "	Guaduas,Sibate")
City.create(:id => 432	,:country_id => 9	,:city => "	La Mesa")
City.create(:id => 433	,:country_id => 9	,:city => "	Pacho")
City.create(:id => 434	,:country_id => 9	,:city => "	Villeta")
City.create(:id => 435	,:country_id => 9	,:city => "	Tocancipa")
City.create(:id => 436	,:country_id => 9	,:city => "	La Calera")
City.create(:id => 437	,:country_id => 9	,:city => "	Silvania")
City.create(:id => 438	,:country_id => 9	,:city => "	Sopo")
City.create(:id => 439	,:country_id => 9	,:city => "	Tabio")
City.create(:id => 440	,:country_id => 9	,:city => "	El Colegio")
City.create(:id => 441	,:country_id => 9	,:city => "	Cota")
City.create(:id => 442	,:country_id => 9	,:city => "	Choconta")
City.create(:id => 443	,:country_id => 9	,:city => "	Tenjo")
City.create(:id => 444	,:country_id => 9	,:city => "	Cogua")
City.create(:id => 445	,:country_id => 9	,:city => "	Tocaima")
City.create(:id => 446	,:country_id => 9	,:city => "	Villapinzon")
City.create(:id => 447	,:country_id => 9	,:city => "	Caparrapi")
City.create(:id => 448	,:country_id => 9	,:city => "	Caqueza")
City.create(:id => 449	,:country_id => 9	,:city => "	Yacopi")
City.create(:id => 450	,:country_id => 9	,:city => "	Puerto Salgar")
City.create(:id => 451	,:country_id => 9	,:city => "	Suesca")
City.create(:id => 452	,:country_id => 9	,:city => "	Nilo")
City.create(:id => 453	,:country_id => 9	,:city => "	Viota")
City.create(:id => 454	,:country_id => 9	,:city => "	El Rosal")
City.create(:id => 455	,:country_id => 9	,:city => "	Anolaima")
City.create(:id => 456	,:country_id => 9	,:city => "	La Vega")
City.create(:id => 457	,:country_id => 9	,:city => "	Subachoque")
City.create(:id => 458	,:country_id => 9	,:city => "	Guasca")
City.create(:id => 459	,:country_id => 9	,:city => "	San Antonio del Tequendama")
City.create(:id => 460	,:country_id => 9	,:city => "	Fomeque")
City.create(:id => 461	,:country_id => 9	,:city => "	Ubala")
City.create(:id => 462	,:country_id => 9	,:city => "	Agua de Dios")
City.create(:id => 463	,:country_id => 9	,:city => "	Arbelaez")
City.create(:id => 464	,:country_id => 9	,:city => "	Guacheta")
City.create(:id => 465	,:country_id => 9	,:city => "	Anapoima")
City.create(:id => 466	,:country_id => 9	,:city => "	Nemocon")
City.create(:id => 467	,:country_id => 9	,:city => "	Choachi")
City.create(:id => 468	,:country_id => 9	,:city => "	Pasca")
City.create(:id => 469	,:country_id => 9	,:city => "	Simijaca")
City.create(:id => 470	,:country_id => 9	,:city => "	Gachancipa")
City.create(:id => 471	,:country_id => 9	,:city => "	Gacheta")
City.create(:id => 472	,:country_id => 9	,:city => "	San Bernardo")
City.create(:id => 473	,:country_id => 9	,:city => "	Sasaima")
City.create(:id => 474	,:country_id => 9	,:city => "	Cachipay")
City.create(:id => 475	,:country_id => 9	,:city => "	La Palma")
City.create(:id => 476	,:country_id => 9	,:city => "	Medina")
City.create(:id => 477	,:country_id => 9	,:city => "	Sesquile")
City.create(:id => 478	,:country_id => 9	,:city => "	San Juan de Rio Seco")
City.create(:id => 479	,:country_id => 9	,:city => "	Susa")
City.create(:id => 480	,:country_id => 9	,:city => "	Lenguazaque")
City.create(:id => 481	,:country_id => 9	,:city => "	Bojaca")
City.create(:id => 482	,:country_id => 9	,:city => "	Carmen de Carupa")
City.create(:id => 483	,:country_id => 9	,:city => "	Junin,Chipaque")
City.create(:id => 484	,:country_id => 9	,:city => "	San Francisco")
City.create(:id => 485	,:country_id => 9	,:city => "	Quipile")
City.create(:id => 486	,:country_id => 9	,:city => "	Ricaurte")
City.create(:id => 487	,:country_id => 9	,:city => "	Une")
City.create(:id => 488	,:country_id => 9	,:city => "	Apulo")
City.create(:id => 489	,:country_id => 9	,:city => "	Nocaima")
City.create(:id => 490	,:country_id => 9	,:city => "	Vergara")
City.create(:id => 491	,:country_id => 9	,:city => "	Tausa")
City.create(:id => 492	,:country_id => 9	,:city => "	Tena")
City.create(:id => 493	,:country_id => 9	,:city => "	Paratebueno")
City.create(:id => 494	,:country_id => 9	,:city => "	Cucunuba")
City.create(:id => 495	,:country_id => 9	,:city => "	La Pena")
City.create(:id => 496	,:country_id => 9	,:city => "	Ubaque")
City.create(:id => 497	,:country_id => 9	,:city => "	Granada")
City.create(:id => 498	,:country_id => 9	,:city => "	Macheta")
City.create(:id => 499	,:country_id => 9	,:city => "	Guatavita")
City.create(:id => 500	,:country_id => 9	,:city => "	Fosca")
City.create(:id => 501	,:country_id => 9	,:city => "	Quetame")
City.create(:id => 502	,:country_id => 9	,:city => "	Alban")
City.create(:id => 503	,:country_id => 9	,:city => "	Gachala")
City.create(:id => 504	,:country_id => 9	,:city => "	Nimaima")
City.create(:id => 505	,:country_id => 9	,:city => "	Paime")
City.create(:id => 506	,:country_id => 9	,:city => "	Pandi")
City.create(:id => 507	,:country_id => 9	,:city => "	San Cayetano")
City.create(:id => 508	,:country_id => 9	,:city => "	Fuquene")
City.create(:id => 509	,:country_id => 9	,:city => "	Zipacon")
City.create(:id => 510	,:country_id => 9	,:city => "	El Penon")
City.create(:id => 511	,:country_id => 9	,:city => "	Supata")
City.create(:id => 512	,:country_id => 9	,:city => "	utica")
City.create(:id => 513	,:country_id => 9	,:city => "	Tibacuy")
City.create(:id => 514	,:country_id => 9	,:city => "	Topaipi")
City.create(:id => 515	,:country_id => 9	,:city => "	Guayabetal")
City.create(:id => 516	,:country_id => 9	,:city => "	Sutatausa")
City.create(:id => 517	,:country_id => 9	,:city => "	Quebradanegra")
City.create(:id => 518	,:country_id => 9	,:city => "	Cabrera")
City.create(:id => 519	,:country_id => 9	,:city => "	Manta")
City.create(:id => 520	,:country_id => 9	,:city => "	Viani")
City.create(:id => 521	,:country_id => 9	,:city => "	Chaguani")
City.create(:id => 522	,:country_id => 9	,:city => "	Venecia")
City.create(:id => 523	,:country_id => 9	,:city => "	Gama")
City.create(:id => 524	,:country_id => 9	,:city => "	Guayabal de Siquima")
City.create(:id => 525	,:country_id => 9	,:city => "	Gutierrez")
City.create(:id => 526	,:country_id => 9	,:city => "	Tibirita")
City.create(:id => 527	,:country_id => 9	,:city => "	Puli")
City.create(:id => 528	,:country_id => 9	,:city => "	Jerusalen")
City.create(:id => 529	,:country_id => 9	,:city => "	Bituima")
City.create(:id => 530	,:country_id => 9	,:city => "	Guataqui")
City.create(:id => 531	,:country_id => 9	,:city => "	Villagomez")
City.create(:id => 532	,:country_id => 9	,:city => "	Narino")
City.create(:id => 533	,:country_id => 9	,:city => "	Beltran")
City.create(:id => 534	,:country_id => 10	,:city => "	Pereira")
City.create(:id => 535	,:country_id => 10	,:city => "	Santa Rosa de Cabal")
City.create(:id => 536	,:country_id => 10	,:city => "	La Virginia")
City.create(:id => 537	,:country_id => 10	,:city => "	Belen de Umbria")
City.create(:id => 538	,:country_id => 10	,:city => "	Marsella")
City.create(:id => 539	,:country_id => 10	,:city => "	Santuario")
City.create(:id => 540	,:country_id => 10	,:city => "	Mistrato")
City.create(:id => 541	,:country_id => 10	,:city => "	Pueblo Rico")
City.create(:id => 542	,:country_id => 11	,:city => "	Santa Marta")
City.create(:id => 543	,:country_id => 11	,:city => "	Zona Bananera")
City.create(:id => 544	,:country_id => 11	,:city => "	Baranoa")
City.create(:id => 545	,:country_id => 11	,:city => "	El Banco")
City.create(:id => 546	,:country_id => 11	,:city => "	Zona Bananera")
City.create(:id => 547	,:country_id => 11	,:city => "	El Banco")
City.create(:id => 548	,:country_id => 11	,:city => "	Plato")
City.create(:id => 549	,:country_id => 11	,:city => "	Pivijay")
City.create(:id => 550	,:country_id => 11	,:city => "	Aracataca")
City.create(:id => 551	,:country_id => 11	,:city => "	Ariguani")
City.create(:id => 552	,:country_id => 11	,:city => "	Sitionuevo")
City.create(:id => 553	,:country_id => 11	,:city => "	Guamal")
City.create(:id => 554	,:country_id => 11	,:city => "	Puebloviejo")
City.create(:id => 555	,:country_id => 11	,:city => "	Santa Ana")
City.create(:id => 556	,:country_id => 11	,:city => "	El Reten")
City.create(:id => 557	,:country_id => 11	,:city => "	San Sebastian de Buenavista")
City.create(:id => 558	,:country_id => 11	,:city => "	El Pinon")
City.create(:id => 559	,:country_id => 11	,:city => "	Chivolo")
City.create(:id => 560	,:country_id => 11	,:city => "	Nueva Granada")
City.create(:id => 561	,:country_id => 11	,:city => "	Sabanas de San angel")
City.create(:id => 562	,:country_id => 11	,:city => "	Pijino del Carmen")
City.create(:id => 563	,:country_id => 11	,:city => "	Tenerife")
City.create(:id => 564	,:country_id => 11	,:city => "	Algarrobo")
City.create(:id => 565	,:country_id => 11	,:city => "	Santa Barbara de Pinto")
City.create(:id => 566	,:country_id => 11	,:city => "	Concordia")
City.create(:id => 567	,:country_id => 11	,:city => "	San Zenon")
City.create(:id => 568	,:country_id => 11	,:city => "	Remolino")
City.create(:id => 569	,:country_id => 11	,:city => "	Zapayan")
City.create(:id => 570	,:country_id => 11	,:city => "	Salamina")
City.create(:id => 571	,:country_id => 11	,:city => "	Cerro San Antonio"	)
City.create(:id => 572	,:country_id => 12	,:city => "	Villavicencio")
City.create(:id => 573	,:country_id => 12	,:city => "	Acacias")
City.create(:id => 574	,:country_id => 12	,:city => "	Granada")
City.create(:id => 575	,:country_id => 12	,:city => "	Puerto Lopez")
City.create(:id => 576	,:country_id => 12	,:city => "	La Macarena")
City.create(:id => 577	,:country_id => 12	,:city => "	San Martin")
City.create(:id => 578	,:country_id => 12	,:city => "	Vista Hermosa")
City.create(:id => 579	,:country_id => 12	,:city => "	Puerto Rico")
City.create(:id => 580	,:country_id => 12	,:city => "	Puerto Gaitan")
City.create(:id => 581	,:country_id => 12	,:city => "	Cumaral")
City.create(:id => 582	,:country_id => 12	,:city => "	Puerto Concordia")
City.create(:id => 583	,:country_id => 12	,:city => "	La Uribe")
City.create(:id => 584	,:country_id => 12	,:city => "	Fuente de Oro")
City.create(:id => 585	,:country_id => 12	,:city => "	Mesetas")
City.create(:id => 586	,:country_id => 12	,:city => "	Puerto Lleras")
City.create(:id => 587	,:country_id => 12	,:city => "	San Juan de Arama")
City.create(:id => 588	,:country_id => 12	,:city => "	San Carlos de Guaroa")
City.create(:id => 589	,:country_id => 12	,:city => "	Cubarral")
City.create(:id => 590	,:country_id => 12	,:city => "	San Juanito")
City.create(:id => 591	,:country_id => 13	,:city => "	Valledupar")
City.create(:id => 592	,:country_id => 13	,:city => "	Agustin Codazzi")
City.create(:id => 593	,:country_id => 13	,:city => "	Agustin Codazzi")
City.create(:id => 594	,:country_id => 13	,:city => "	Chimichagua")
City.create(:id => 595	,:country_id => 13	,:city => "	Bosconia")
City.create(:id => 596	,:country_id => 13	,:city => "	El Copey")
City.create(:id => 597	,:country_id => 13	,:city => "	Chiriguana")
City.create(:id => 598	,:country_id => 13	,:city => "	La Jagua de Ibirico")
City.create(:id => 599	,:country_id => 13	,:city => "	La Paz")
City.create(:id => 600	,:country_id => 13	,:city => "	El Paso")
City.create(:id => 601	,:country_id => 13	,:city => "	San Alberto")
City.create(:id => 602	,:country_id => 13	,:city => "	Astrea")
City.create(:id => 603	,:country_id => 13	,:city => "	San Martin")
City.create(:id => 604	,:country_id => 13	,:city => "	Pueblo Bello")
City.create(:id => 605	,:country_id => 13	,:city => "	Pelaya")
City.create(:id => 606	,:country_id => 13	,:city => "	Pailitas")
City.create(:id => 607	,:country_id => 13	,:city => "	La Gloria")
City.create(:id => 608	,:country_id => 13	,:city => "	Rio de Oro")
City.create(:id => 609	,:country_id => 13	,:city => "	Tamalameque")
City.create(:id => 610	,:country_id => 13	,:city => "	Becerril")
City.create(:id => 611	,:country_id => 13	,:city => "	San Diego")
City.create(:id => 612	,:country_id => 13	,:city => "	Gonzalez")
City.create(:id => 613	,:country_id => 14	,:city => "	Pasto")
City.create(:id => 614	,:country_id => 14	,:city => "	Tumaco")
City.create(:id => 615	,:country_id => 14	,:city => "	Ipiales")
City.create(:id => 616	,:country_id => 14	,:city => "	Samaniego")
City.create(:id => 617	,:country_id => 14	,:city => "	Tuquerres")
City.create(:id => 618	,:country_id => 14	,:city => "	Cumbal")
City.create(:id => 619	,:country_id => 14	,:city => "	Barbacoas")
City.create(:id => 620	,:country_id => 14	,:city => "	La Union")
City.create(:id => 621	,:country_id => 14	,:city => "	Olaya Herrera")
City.create(:id => 622	,:country_id => 14	,:city => "	El Charco")
City.create(:id => 623	,:country_id => 14	,:city => "	Sandona")
City.create(:id => 624	,:country_id => 14	,:city => "	Buesaco")
City.create(:id => 625	,:country_id => 14	,:city => "	Santacruz")
City.create(:id => 626	,:country_id => 14	,:city => "	Alban")
City.create(:id => 627	,:country_id => 14	,:city => "	Pupiales")
City.create(:id => 628	,:country_id => 14	,:city => "	San Lorenzo")
City.create(:id => 629	,:country_id => 14	,:city => "	San Pablo")
City.create(:id => 630	,:country_id => 14	,:city => "	La Cruz")
City.create(:id => 631	,:country_id => 14	,:city => "	Taminango")
City.create(:id => 632	,:country_id => 14	,:city => "	Roberto Payan")
City.create(:id => 633	,:country_id => 14	,:city => "	Guachucal")
City.create(:id => 634	,:country_id => 14	,:city => "	Magui Payan")
City.create(:id => 635	,:country_id => 14	,:city => "	Los Andes")
City.create(:id => 636	,:country_id => 14	,:city => "	Santa Barbara")
City.create(:id => 637	,:country_id => 14	,:city => "	Ricaurte")
City.create(:id => 638	,:country_id => 14	,:city => "	San Bernardo")
City.create(:id => 639	,:country_id => 14	,:city => "	El Tambo")
City.create(:id => 640	,:country_id => 14	,:city => "	El Tablon")
City.create(:id => 641	,:country_id => 14	,:city => "	Policarpa")
City.create(:id => 642	,:country_id => 14	,:city => "	Guaitarilla")
City.create(:id => 643	,:country_id => 14	,:city => "	Cordoba")
City.create(:id => 644	,:country_id => 14	,:city => "	Potosi")
City.create(:id => 645	,:country_id => 14	,:city => "	Leiva")
City.create(:id => 646	,:country_id => 14	,:city => "	Providencia")
City.create(:id => 647	,:country_id => 14	,:city => "	Cumbitara")
City.create(:id => 648	,:country_id => 14	,:city => "	La Florida")
City.create(:id => 649	,:country_id => 14	,:city => "	El Rosario")
City.create(:id => 650	,:country_id => 14	,:city => "	Francisco Pizarro")
City.create(:id => 651	,:country_id => 14	,:city => "	Tangua,Consaca")
City.create(:id => 652	,:country_id => 14	,:city => "	Yacuanquer")
City.create(:id => 653	,:country_id => 14	,:city => "	Colon")
City.create(:id => 654	,:country_id => 14	,:city => "	Mallama")
City.create(:id => 655	,:country_id => 14	,:city => "	Ancuya")
City.create(:id => 656	,:country_id => 14	,:city => "	Puerres")
City.create(:id => 657	,:country_id => 14	,:city => "	La Tola")
City.create(:id => 658	,:country_id => 14	,:city => "	Ospina")
City.create(:id => 659	,:country_id => 14	,:city => "	Iles")
City.create(:id => 660	,:country_id => 14	,:city => "	Imues")
City.create(:id => 661	,:country_id => 14	,:city => "	Sapuyes")
City.create(:id => 662	,:country_id => 14	,:city => "	Arboleda")
City.create(:id => 663	,:country_id => 14	,:city => "	San Pedro de Cartago")
City.create(:id => 664	,:country_id => 14	,:city => "	El Penol")
City.create(:id => 665	,:country_id => 14	,:city => "	Aldana")
City.create(:id => 666	,:country_id => 14	,:city => "	Contadero")
City.create(:id => 667	,:country_id => 14	,:city => "	Belen")
City.create(:id => 668	,:country_id => 14	,:city => "	La Llanada")
City.create(:id => 669	,:country_id => 14	,:city => "	Gualmatan")
City.create(:id => 670	,:country_id => 14	,:city => "	Narino")
City.create(:id => 671	,:country_id => 15	,:city => "	Monteria")
City.create(:id => 672	,:country_id => 15	,:city => "	Tierralta")
City.create(:id => 673	,:country_id => 15	,:city => "	Cerete")
City.create(:id => 674	,:country_id => 15	,:city => "	Sahagun")
City.create(:id => 675	,:country_id => 15	,:city => "	Montelibano")
City.create(:id => 676	,:country_id => 15	,:city => "	Cienaga de Oro")
City.create(:id => 677	,:country_id => 15	,:city => "	Chinu")
City.create(:id => 678	,:country_id => 15	,:city => "	Ayapel")
City.create(:id => 679	,:country_id => 15	,:city => "	San Pelayo")
City.create(:id => 680	,:country_id => 15	,:city => "	Puerto Libertador")
City.create(:id => 681	,:country_id => 15	,:city => "	Valencia")
City.create(:id => 682	,:country_id => 15	,:city => "	Pueblo Nuevo")
City.create(:id => 683	,:country_id => 15	,:city => "	San Bernardo del Viento")
City.create(:id => 684	,:country_id => 15	,:city => "	San Antero")
City.create(:id => 685	,:country_id => 15	,:city => "	San Carlos")
City.create(:id => 686	,:country_id => 15	,:city => "	Monitos")
City.create(:id => 687	,:country_id => 15	,:city => "	Puerto Escondido")
City.create(:id => 688	,:country_id => 15	,:city => "	Buenavista")
City.create(:id => 689	,:country_id => 15	,:city => "	Los Cordobas")
City.create(:id => 690	,:country_id => 15	,:city => "	Canalete")
City.create(:id => 691	,:country_id => 15	,:city => "	Cotorra")
City.create(:id => 692	,:country_id => 15	,:city => "	Purisima")
City.create(:id => 693	,:country_id => 15	,:city => "	Momil")
City.create(:id => 694	,:country_id => 15	,:city => "	Chima")
City.create(:id => 695	,:country_id => 16	,:city => "	Manizales")
City.create(:id => 696	,:country_id => 16	,:city => "	La Dorada")
City.create(:id => 697	,:country_id => 16	,:city => "	Riosucio")
City.create(:id => 698	,:country_id => 16	,:city => "	Chinchina")
City.create(:id => 699	,:country_id => 16	,:city => "	Villamaria")
City.create(:id => 700	,:country_id => 16	,:city => "	Anserma")
City.create(:id => 701	,:country_id => 16	,:city => "	Neira")
City.create(:id => 702	,:country_id => 16	,:city => "	Pensilvania")
City.create(:id => 703	,:country_id => 16	,:city => "	Samana")
City.create(:id => 704	,:country_id => 16	,:city => "	Manzanares")
City.create(:id => 705	,:country_id => 16	,:city => "	Supia")
City.create(:id => 706	,:country_id => 16	,:city => "	Aguadas")
City.create(:id => 707	,:country_id => 16	,:city => "	Salamina")
City.create(:id => 708	,:country_id => 16	,:city => "	Palestina")
City.create(:id => 709	,:country_id => 16	,:city => "	Pacora")
City.create(:id => 710	,:country_id => 16	,:city => "	Marquetalia")
City.create(:id => 711	,:country_id => 16	,:city => "	Aranzazu")
City.create(:id => 712	,:country_id => 16	,:city => "	Filadelfia")
City.create(:id => 713	,:country_id => 16	,:city => "	Belalcazar")
City.create(:id => 714	,:country_id => 16	,:city => "	Risaralda")
City.create(:id => 715	,:country_id => 16	,:city => "	Victoria")
City.create(:id => 716	,:country_id => 16	,:city => "	Marmato")
City.create(:id => 717	,:country_id => 16	,:city => "	San Jose")
City.create(:id => 718	,:country_id => 16	,:city => "	Norcasia")
City.create(:id => 719	,:country_id => 16	,:city => "	La Merced")
City.create(:id => 720	,:country_id => 16	,:city => "	Marulanda")
City.create(:id => 721	,:country_id => 17	,:city => "	Neiva")
City.create(:id => 722	,:country_id => 17	,:city => "	Pitalito")
City.create(:id => 723	,:country_id => 17	,:city => "	Garzon")
City.create(:id => 724	,:country_id => 17	,:city => "	La Plata")
City.create(:id => 725	,:country_id => 17	,:city => "	Campoalegre")
City.create(:id => 726	,:country_id => 17	,:city => "	San Agustin")
City.create(:id => 727	,:country_id => 17	,:city => "	Gigante")
City.create(:id => 728	,:country_id => 17	,:city => "	Palermo")
City.create(:id => 729	,:country_id => 17	,:city => "	Acevedo")
City.create(:id => 730	,:country_id => 17	,:city => "	Isnos")
City.create(:id => 731	,:country_id => 17	,:city => "	Algeciras")
City.create(:id => 732	,:country_id => 17	,:city => "	Timana")
City.create(:id => 733	,:country_id => 17	,:city => "	Aipe")
City.create(:id => 734	,:country_id => 17	,:city => "	Guadalupe")
City.create(:id => 735	,:country_id => 17	,:city => "	Tarqui")
City.create(:id => 736	,:country_id => 17	,:city => "	Suaza")
City.create(:id => 737	,:country_id => 17	,:city => "	Tello")
City.create(:id => 738	,:country_id => 17	,:city => "	Pital")
City.create(:id => 739	,:country_id => 17	,:city => "	La Argentina")
City.create(:id => 740	,:country_id => 17	,:city => "	Colombia")
City.create(:id => 741	,:country_id => 17	,:city => "	Iquira")
City.create(:id => 742	,:country_id => 17	,:city => "	Palestina")
City.create(:id => 743	,:country_id => 17	,:city => "	Saladoblanco")
City.create(:id => 744	,:country_id => 17	,:city => "	Santa Maria")
City.create(:id => 745	,:country_id => 17	,:city => "	Baraya")
City.create(:id => 746	,:country_id => 17	,:city => "	Tesalia")
City.create(:id => 747	,:country_id => 17	,:city => "	Agrado")
City.create(:id => 748	,:country_id => 17	,:city => "	Teruel")
City.create(:id => 749	,:country_id => 17	,:city => "	Yaguara")
City.create(:id => 750	,:country_id => 17	,:city => "	Villavieja")
City.create(:id => 751	,:country_id => 17	,:city => "	Hobo")
City.create(:id => 752	,:country_id => 17	,:city => "	Paicol")
City.create(:id => 753	,:country_id => 17	,:city => "	Altamira")
City.create(:id => 754	,:country_id => 17	,:city => "	Elias")
City.create(:id => 755	,:country_id => 18	,:city => "	Armenia")
City.create(:id => 756	,:country_id => 18	,:city => "	Calarca")
City.create(:id => 757	,:country_id => 18	,:city => "	Montenegro")
City.create(:id => 758	,:country_id => 18	,:city => "	La Tebaida")
City.create(:id => 759	,:country_id => 18	,:city => "	Circasia")
City.create(:id => 760	,:country_id => 18	,:city => "	Filandia")
City.create(:id => 761	,:country_id => 18	,:city => "	Genova")
City.create(:id => 762	,:country_id => 18	,:city => "	Salento")
City.create(:id => 763	,:country_id => 18	,:city => "	Pijao")
City.create(:id => 764	,:country_id => 18	,:city => "	Cordoba")
City.create(:id => 765	,:country_id => 18	,:city => "	Buenavista")
City.create(:id => 766	,:country_id => 19	,:city => "	Popayan")
City.create(:id => 767	,:country_id => 19	,:city => "	El Tambo")
City.create(:id => 768	,:country_id => 19	,:city => "	Puerto Tejada")
City.create(:id => 769	,:country_id => 19	,:city => "	Bolivar")
City.create(:id => 770	,:country_id => 19	,:city => "	La Vega")
City.create(:id => 771	,:country_id => 19	,:city => "	Caloto")
City.create(:id => 772	,:country_id => 19	,:city => "	Piendamo")
City.create(:id => 773	,:country_id => 19	,:city => "	Cajibio")
City.create(:id => 774	,:country_id => 19	,:city => "	Miranda")
City.create(:id => 775	,:country_id => 19	,:city => "	Patia")
City.create(:id => 776	,:country_id => 19	,:city => "	Paez")
City.create(:id => 777	,:country_id => 19	,:city => "	Silvia")
City.create(:id => 778	,:country_id => 19	,:city => "	Caldono")
City.create(:id => 779	,:country_id => 19	,:city => "	Timbio")
City.create(:id => 780	,:country_id => 19	,:city => "	Guapi")
City.create(:id => 781	,:country_id => 19	,:city => "	Corinto")
City.create(:id => 782	,:country_id => 19	,:city => "	Inza")
City.create(:id => 783	,:country_id => 19	,:city => "	Buenos Aires")
City.create(:id => 784	,:country_id => 19	,:city => "	Toribio")
City.create(:id => 785	,:country_id => 19	,:city => "	Argelia")
City.create(:id => 786	,:country_id => 19	,:city => "	Morales")
City.create(:id => 787	,:country_id => 19	,:city => "	Balboa")
City.create(:id => 788	,:country_id => 19	,:city => "	Timbiqui")
City.create(:id => 789	,:country_id => 19	,:city => "	Almaguer")
City.create(:id => 790	,:country_id => 19	,:city => "	Lopez")
City.create(:id => 791	,:country_id => 19	,:city => "	Suarez")
City.create(:id => 792	,:country_id => 19	,:city => "	Mercaderes")
City.create(:id => 793	,:country_id => 19	,:city => "	Totoro")
City.create(:id => 794	,:country_id => 19	,:city => "	Sotara")
City.create(:id => 795	,:country_id => 19	,:city => "	Purace Coconuco")
City.create(:id => 796	,:country_id => 19	,:city => "	Jambalo")
City.create(:id => 797	,:country_id => 19	,:city => "	Villa Rica")
City.create(:id => 798	,:country_id => 19	,:city => "	San Sebastian")
City.create(:id => 799	,:country_id => 19	,:city => "	Rosas")
City.create(:id => 800	,:country_id => 19	,:city => "	La Sierra")
City.create(:id => 801	,:country_id => 19	,:city => "	Santa Rosa")
City.create(:id => 802	,:country_id => 19	,:city => "	Sucre")
City.create(:id => 803	,:country_id => 19	,:city => "	Piamonte")
City.create(:id => 804	,:country_id => 19	,:city => "	Florencia")
City.create(:id => 805	,:country_id => 20	,:city => "	Sincelejo")
City.create(:id => 806	,:country_id => 20	,:city => "	Corozal")
City.create(:id => 807	,:country_id => 20	,:city => "	San Marcos")
City.create(:id => 808	,:country_id => 20	,:city => "	San Onofre")
City.create(:id => 809	,:country_id => 20	,:city => "	Sampues")
City.create(:id => 810	,:country_id => 20	,:city => "	Santiago de Tolu")
City.create(:id => 811	,:country_id => 20	,:city => "	San Benito Abad")
City.create(:id => 812	,:country_id => 20	,:city => "	Sucre,Ovejas")
City.create(:id => 813	,:country_id => 20	,:city => "	Tolu Viejo")
City.create(:id => 814	,:country_id => 20	,:city => "	Galeras")
City.create(:id => 815	,:country_id => 20	,:city => "	San Pedro")
City.create(:id => 816	,:country_id => 20	,:city => "	Guaranda")
City.create(:id => 817	,:country_id => 20	,:city => "	Morroa")
City.create(:id => 818	,:country_id => 20	,:city => "	San Juan de Betulia")
City.create(:id => 819	,:country_id => 20	,:city => "	Palmito")
City.create(:id => 820	,:country_id => 20	,:city => "	Covenas")
City.create(:id => 821	,:country_id => 20	,:city => "	Caimito")
City.create(:id => 822	,:country_id => 20	,:city => "	La Union")
City.create(:id => 823	,:country_id => 20	,:city => "	El Roble")
City.create(:id => 824	,:country_id => 20	,:city => "	Buenavista")
City.create(:id => 825	,:country_id => 20	,:city => "	Coloso")
City.create(:id => 826	,:country_id => 21	,:city => "	Riohacha")
City.create(:id => 827	,:country_id => 21	,:city => "	Uribia")
City.create(:id => 828	,:country_id => 21	,:city => "	Maicao")
City.create(:id => 829	,:country_id => 21	,:city => "	Manaure")
City.create(:id => 830	,:country_id => 21	,:city => "	Barrancas")
City.create(:id => 831	,:country_id => 21	,:city => "	Villanueva")
City.create(:id => 832	,:country_id => 21	,:city => "	Dibulla")
City.create(:id => 833	,:country_id => 21	,:city => "	Albania")
City.create(:id => 834	,:country_id => 21	,:city => "	Urumita")
City.create(:id => 835	,:country_id => 21	,:city => "	Distraccion")
City.create(:id => 836	,:country_id => 21	,:city => "	El Molino")
City.create(:id => 837	,:country_id => 22	,:city => "	Tunja")
City.create(:id => 838	,:country_id => 22	,:city => "	Sogamoso")
City.create(:id => 839	,:country_id => 22	,:city => "	Duitama")
City.create(:id => 840	,:country_id => 22	,:city => "	Chiquinquira")
City.create(:id => 841	,:country_id => 22	,:city => "	Puerto Boyaca")
City.create(:id => 842	,:country_id => 22	,:city => "	Paipa")
City.create(:id => 843	,:country_id => 22	,:city => "	Moniquira")
City.create(:id => 844	,:country_id => 22	,:city => "	Samaca")
City.create(:id => 845	,:country_id => 22	,:city => "	Aquitania")
City.create(:id => 846	,:country_id => 22	,:city => "	Garagoa")
City.create(:id => 847	,:country_id => 22	,:city => "	Nobsa")
City.create(:id => 848	,:country_id => 22	,:city => "	Ventaquemada")
City.create(:id => 849	,:country_id => 22	,:city => "	Santa Rosa de Viterbo")
City.create(:id => 850	,:country_id => 22	,:city => "	Combita,Saboya")
City.create(:id => 851	,:country_id => 22	,:city => "	Tibasosa")
City.create(:id => 852	,:country_id => 22	,:city => "	Raquira")
City.create(:id => 853	,:country_id => 22	,:city => "	Villa de Leyva")
City.create(:id => 854	,:country_id => 22	,:city => "	Chita")
City.create(:id => 855	,:country_id => 22	,:city => "	Ramiriqui")
City.create(:id => 856	,:country_id => 22	,:city => "	Toca")
City.create(:id => 857	,:country_id => 22	,:city => "	Otanche")
City.create(:id => 858	,:country_id => 22	,:city => "	Pauna")
City.create(:id => 859	,:country_id => 22	,:city => "	Socota")
City.create(:id => 860	,:country_id => 22	,:city => "	Muzo")
City.create(:id => 861	,:country_id => 22	,:city => "	Guateque")
City.create(:id => 862	,:country_id => 22	,:city => "	Umbita")
City.create(:id => 863	,:country_id => 22	,:city => "	Pesca")
City.create(:id => 864	,:country_id => 22	,:city => "	Tibana")
City.create(:id => 865	,:country_id => 22	,:city => "	Miraflores")
City.create(:id => 866	,:country_id => 22	,:city => "	Soata")
City.create(:id => 867	,:country_id => 22	,:city => "	Tuta")
City.create(:id => 868	,:country_id => 22	,:city => "	Sotaquira")
City.create(:id => 869	,:country_id => 22	,:city => "	Siachoque")
City.create(:id => 870	,:country_id => 22	,:city => "	Boavita")
City.create(:id => 871	,:country_id => 22	,:city => "	Quipama")
City.create(:id => 872	,:country_id => 22	,:city => "	Maripi")
City.create(:id => 873	,:country_id => 22	,:city => "	Guican")
City.create(:id => 874	,:country_id => 22	,:city => "	Socha")
City.create(:id => 875	,:country_id => 22	,:city => "	Turmeque")
City.create(:id => 876	,:country_id => 22	,:city => "	Jenesano")
City.create(:id => 877	,:country_id => 22	,:city => "	Tasco")
City.create(:id => 878	,:country_id => 22	,:city => "	Motavita")
City.create(:id => 879	,:country_id => 22	,:city => "	Chitaraque")
City.create(:id => 880	,:country_id => 22	,:city => "	Cubara")
City.create(:id => 881	,:country_id => 22	,:city => "	San Luis de Gaceno")
City.create(:id => 882	,:country_id => 22	,:city => "	Guayata")
City.create(:id => 883	,:country_id => 22	,:city => "	Sutamarchan")
City.create(:id => 884	,:country_id => 22	,:city => "	Nuevo Colon")
City.create(:id => 885	,:country_id => 22	,:city => "	Chiquiza")
City.create(:id => 886	,:country_id => 22	,:city => "	Soraca")
City.create(:id => 887	,:country_id => 22	,:city => "	Buenavista")
City.create(:id => 888	,:country_id => 22	,:city => "	San Jose de Pare")
City.create(:id => 889	,:country_id => 22	,:city => "	Tota,Gameza")
City.create(:id => 890	,:country_id => 22	,:city => "	El Cocuy")
City.create(:id => 891	,:country_id => 22	,:city => "	Chiscas")
City.create(:id => 892	,:country_id => 22	,:city => "	Labranzagrande")
City.create(:id => 893	,:country_id => 22	,:city => "	Mongua")
City.create(:id => 894	,:country_id => 22	,:city => "	Paz de Rio")
City.create(:id => 895	,:country_id => 22	,:city => "	Cienega")
City.create(:id => 896	,:country_id => 22	,:city => "	Togui")
City.create(:id => 897	,:country_id => 22	,:city => "	Arcabuco")
City.create(:id => 898	,:country_id => 22	,:city => "	Zetaquira")
City.create(:id => 899	,:country_id => 22	,:city => "	Boyaca")
City.create(:id => 900	,:country_id => 22	,:city => "	Chivata")
City.create(:id => 901	,:country_id => 22	,:city => "	Mongui")
City.create(:id => 902	,:country_id => 22	,:city => "	Floresta")
City.create(:id => 903	,:country_id => 22	,:city => "	San Mateo")
City.create(:id => 904	,:country_id => 22	,:city => "	Jerico")
City.create(:id => 905	,:country_id => 22	,:city => "	Macanal")
City.create(:id => 906	,:country_id => 22	,:city => "	Tenza")
City.create(:id => 907	,:country_id => 22	,:city => "	Santa Maria")
City.create(:id => 908	,:country_id => 22	,:city => "	San Miguel de Sema")
City.create(:id => 909	,:country_id => 22	,:city => "	Cucaita")
City.create(:id => 910	,:country_id => 22	,:city => "	Sutatenza")
City.create(:id => 911	,:country_id => 22	,:city => "	Somondoco")
City.create(:id => 912	,:country_id => 22	,:city => "	Cerinza")
City.create(:id => 913	,:country_id => 22	,:city => "	Coper")
City.create(:id => 914	,:country_id => 22	,:city => "	Campohermoso")
City.create(:id => 915	,:country_id => 22	,:city => "	Caldas")
City.create(:id => 916	,:country_id => 22	,:city => "	El Espino")
City.create(:id => 917	,:country_id => 22	,:city => "	Sachica")
City.create(:id => 918	,:country_id => 22	,:city => "	Tipacoque")
City.create(:id => 919	,:country_id => 22	,:city => "	Chinavita")
City.create(:id => 920	,:country_id => 22	,:city => "	Susacon")
City.create(:id => 921	,:country_id => 22	,:city => "	Topaga")
City.create(:id => 922	,:country_id => 22	,:city => "	La Uvita")
City.create(:id => 923	,:country_id => 22	,:city => "	Viracacha")
City.create(:id => 924	,:country_id => 22	,:city => "	Paez")
City.create(:id => 925	,:country_id => 22	,:city => "	Covarachia")
City.create(:id => 926	,:country_id => 22	,:city => "	La Capilla")
City.create(:id => 927	,:country_id => 22	,:city => "	Pachavita")
City.create(:id => 928	,:country_id => 22	,:city => "	Gachantiva")
City.create(:id => 929	,:country_id => 22	,:city => "	Rondon")
City.create(:id => 930	,:country_id => 22	,:city => "	Sora")
City.create(:id => 931	,:country_id => 22	,:city => "	Tinjaca")
City.create(:id => 932	,:country_id => 22	,:city => "	Oicata")
City.create(:id => 933	,:country_id => 22	,:city => "	Sativanorte")
City.create(:id => 934	,:country_id => 22	,:city => "	Briceno")
City.create(:id => 935	,:country_id => 22	,:city => "	Paya")
City.create(:id => 936	,:country_id => 22	,:city => "	Corrales")
City.create(:id => 937	,:country_id => 22	,:city => "	Beteitiva")
City.create(:id => 938	,:country_id => 22	,:city => "	Pajarito")
City.create(:id => 939	,:country_id => 22	,:city => "	Tutaza")
City.create(:id => 940	,:country_id => 22	,:city => "	Chivor")
City.create(:id => 941	,:country_id => 22	,:city => "	Guacamayas")
City.create(:id => 942	,:country_id => 22	,:city => "	Iza,Cuitiva")
City.create(:id => 943	,:country_id => 22	,:city => "	San Eduardo")
City.create(:id => 944	,:country_id => 22	,:city => "	Berbeo")
City.create(:id => 945	,:country_id => 22	,:city => "	Panqueba")
City.create(:id => 946	,:country_id => 22	,:city => "	La Victoria")
City.create(:id => 947	,:country_id => 22	,:city => "	Tunungua")
City.create(:id => 948	,:country_id => 22	,:city => "	Pisba")
City.create(:id => 949	,:country_id => 22	,:city => "	Sativasur")
City.create(:id => 950	,:country_id => 22	,:city => "	Busbanza")
City.create(:id => 951	,:country_id => 23	,:city => "	Florencia")
City.create(:id => 952	,:country_id => 23	,:city => "	San Vicente del Caguan")
City.create(:id => 953	,:country_id => 23	,:city => "	Puerto Rico")
City.create(:id => 954	,:country_id => 23	,:city => "	Cartagena del Chaira")
City.create(:id => 955	,:country_id => 23	,:city => "	La Montanita")
City.create(:id => 956	,:country_id => 23	,:city => "	El Doncello")
City.create(:id => 957	,:country_id => 23	,:city => "	Solano")
City.create(:id => 958	,:country_id => 23	,:city => "	El Paujil")
City.create(:id => 959	,:country_id => 23	,:city => "	San Jose del Fragua")
City.create(:id => 960	,:country_id => 23	,:city => "	Milan")
City.create(:id => 961	,:country_id => 23	,:city => "	Curillo")
City.create(:id => 962	,:country_id => 23	,:city => "	Valparaiso")
City.create(:id => 963	,:country_id => 23	,:city => "	Belen de los Andaquies")
City.create(:id => 964	,:country_id => 23	,:city => "	Albania")
City.create(:id => 965	,:country_id => 23	,:city => "	Morelia")
City.create(:id => 966	,:country_id => 24	,:city => "	Yopal")
City.create(:id => 967	,:country_id => 24	,:city => "	Aguazul")
City.create(:id => 968	,:country_id => 24	,:city => "	Tauramena")
City.create(:id => 969	,:country_id => 24	,:city => "	Monterrey")
City.create(:id => 970	,:country_id => 24	,:city => "	Trinidad")
City.create(:id => 971	,:country_id => 24	,:city => "	Mani")
City.create(:id => 972	,:country_id => 24	,:city => "	Hato Corozal")
City.create(:id => 973	,:country_id => 24	,:city => "	Nunchia")
City.create(:id => 974	,:country_id => 24	,:city => "	Pore")
City.create(:id => 975	,:country_id => 24	,:city => "	Orocue")
City.create(:id => 976	,:country_id => 24	,:city => "	San Luis de Palenque")
City.create(:id => 977	,:country_id => 24	,:city => "	Tamara")
City.create(:id => 978	,:country_id => 24	,:city => "	Sabanalarga")
City.create(:id => 979	,:country_id => 24	,:city => "	Recetor")
City.create(:id => 980	,:country_id => 24	,:city => "	Chameza")
City.create(:id => 981	,:country_id => 24	,:city => "	Sacama")
City.create(:id => 982	,:country_id => 24	,:city => "	La Salina")
City.create(:id => 983	,:country_id => 25	,:city => "	Quibdo")
City.create(:id => 984	,:country_id => 25	,:city => "	Alto Baudo")
City.create(:id => 985	,:country_id => 25	,:city => "	Istmina")
City.create(:id => 986	,:country_id => 25	,:city => "	Medio Atrato")
City.create(:id => 987	,:country_id => 25	,:city => "	Riosucio1")
City.create(:id => 988	,:country_id => 25	,:city => "	Belen de Bajira")
City.create(:id => 989	,:country_id => 25	,:city => "	Condoto")
City.create(:id => 990	,:country_id => 25	,:city => "	Medio San Juan")
City.create(:id => 991	,:country_id => 25	,:city => "	Litoral de San Juan")
City.create(:id => 992	,:country_id => 25	,:city => "	Carmen del Atrato")
City.create(:id => 993	,:country_id => 25	,:city => "	Medio Baudo")
City.create(:id => 994	,:country_id => 25	,:city => "	Acandi")
City.create(:id => 995	,:country_id => 25	,:city => "	Lloro")
City.create(:id => 996	,:country_id => 25	,:city => "	Bojaya")
City.create(:id => 997	,:country_id => 25	,:city => "	Certegui")
City.create(:id => 998	,:country_id => 25	,:city => "	Bahia Solano")
City.create(:id => 999	,:country_id => 25	,:city => "	Bagado")
City.create(:id => 1000	,:country_id => 25	,:city => "	Union Panamericana")
City.create(:id => 1001	,:country_id => 25	,:city => "	Rio Iro")
City.create(:id => 1002	,:country_id => 25	,:city => "	Rio Quito")
City.create(:id => 1003	,:country_id => 25	,:city => "	Novita")
City.create(:id => 1004	,:country_id => 25	,:city => "	Nuqui")
City.create(:id => 1005	,:country_id => 25	,:city => "	Atrato")
City.create(:id => 1006	,:country_id => 25	,:city => "	Carmen del Darien")
City.create(:id => 1007	,:country_id => 25	,:city => "	San Jose del Palmar")
City.create(:id => 1008	,:country_id => 25	,:city => "	Sipi")
City.create(:id => 1009	,:country_id => 26	,:city => "	Arauca")
City.create(:id => 1010	,:country_id => 26	,:city => "	Tame")
City.create(:id => 1011	,:country_id => 26	,:city => "	Saravena")
City.create(:id => 1012	,:country_id => 26	,:city => "	Arauquita")
City.create(:id => 1013	,:country_id => 26	,:city => "	Fortul")
City.create(:id => 1014	,:country_id => 26	,:city => "	Puerto Rondon")
City.create(:id => 1015	,:country_id => 27	,:city => "	Providencia")
City.create(:id => 1016	,:country_id => 27	,:city => "	San Andres")
City.create(:id => 1017	,:country_id => 28	,:city => "	San Jose del Guaviare")
City.create(:id => 1018	,:country_id => 28	,:city => "	El Retorno")
City.create(:id => 1019	,:country_id => 28	,:city => "	Miraflores")
City.create(:id => 1020	,:country_id => 28	,:city => "	Calamar")
City.create(:id => 1021	,:country_id => 29	,:city => "	Puerto Asis")
City.create(:id => 1022	,:country_id => 29	,:city => "	Valle del Guamuez")
City.create(:id => 1023	,:country_id => 29	,:city => "	Orito,Mocoa")
City.create(:id => 1024	,:country_id => 29	,:city => "	San Miguel")
City.create(:id => 1025	,:country_id => 29	,:city => "	Villa Garzon")
City.create(:id => 1026	,:country_id => 29	,:city => "	Puerto Caicedo")
City.create(:id => 1027	,:country_id => 29	,:city => "	Santiago")
City.create(:id => 1028	,:country_id => 29	,:city => "	Colon")
City.create(:id => 1029	,:country_id => 30	,:city => "	Leticia")
City.create(:id => 1030	,:country_id => 30	,:city => "	Puerto Narino")
City.create(:id => 1031	,:country_id => 30	,:city => "	El Encanto")
City.create(:id => 1032	,:country_id => 30	,:city => "	Tarapaca")
City.create(:id => 1033	,:country_id => 30	,:city => "	La Chorrera")
City.create(:id => 1034	,:country_id => 30	,:city => "	Puerto Santander")
City.create(:id => 1035	,:country_id => 30	,:city => "	Miriti-Parana")
City.create(:id => 1036	,:country_id => 30	,:city => "	Puerto Arica")
City.create(:id => 1037	,:country_id => 30	,:city => "	Puerto Alegria")
City.create(:id => 1038	,:country_id => 30	,:city => "	La Victoria")
City.create(:id => 1039	,:country_id => 31	,:city => "	Cumaribo")
City.create(:id => 1040	,:country_id => 31	,:city => "	Puerto Carreno")
City.create(:id => 1041	,:country_id => 31	,:city => "	La Primavera")
City.create(:id => 1042	,:country_id => 31	,:city => "	Santa Rosalia")
City.create(:id => 1043	,:country_id => 32	,:city => "	Mitu")
City.create(:id => 1044	,:country_id => 32	,:city => "	Pacoa")
City.create(:id => 1045	,:country_id => 32	,:city => "	Caruru")
City.create(:id => 1046	,:country_id => 32	,:city => "	Yavarate")
City.create(:id => 1047	,:country_id => 32	,:city => "	Taraira")
City.create(:id => 1048	,:country_id => 32	,:city => "	Papunaua")
City.create(:id => 1049	,:country_id => 33	,:city => "	Inirida")
City.create(:id => 1050	,:country_id => 33	,:city => "	Barranco Minas")
City.create(:id => 1051	,:country_id => 33	,:city => "	San Felipe")
City.create(:id => 1052	,:country_id => 33	,:city => "	Morichal")
City.create(:id => 1053	,:country_id => 33	,:city => "	La Guadalupe")